### ISSUE TITLE
Cannot select Diff & Merge tools. "Incorrect Folder Selection: Please select folder at path "(null)" which matches XDG_CONFIG_HOME variable"

### ISSUE THREAD

**Issue by ideologysec** [milke/GitFinder-Issues#105]
When I open GitFinder to configure the Diff & Merge tools under General in Git Configuration, XDG_CONFIG_HOME is set to  `/Users/username/.config` which is all well and good. But, I can't set the diff or merge tools; my only option is "Select tool" which is already checked. I have a `~/.config` folder in my home directory, but I have no git folder in there; I keep my git config in my personal repo elsewhere as mentioned above. Whenever I try to set the path for XDG_CONFIG, I get this error:

<img width="260" alt="Screen Shot 2021-10-25 at 15 30 11" src="https://user-images.githubusercontent.com/790061/138762011-1cd5928d-e936-472b-9d90-99dae27dd72e.png">

Here's my git setup:
`~/.gitconfig` is a symlink to `~/Developer/dotfiles/.gitspecialconf`, and I have 

```ini
[core]
	excludesfile = /Users/username/Developer/dotfiles/.gitignore
```
inside the symlinked gitconfig.

I also already have Kaleidoscope set up as the diff & merge tools inside that gitconfig:

```ini
[difftool "Kaleidoscope"]
    cmd = ksdiff --partial-changeset --relative-path \"$MERGED\" -- \"$LOCAL\" \"$REMOTE\"
[difftool]
    prompt = false
[diff]
    tool = Kaleidoscope
    renames = copies
    colorMoved = default

[mergetool "Kaleidoscope"]
    cmd = ksdiff --merge --output \"$MERGED\" --base \"$BASE\" -- \"$LOCAL\" \"$REMOTE\"
  # If you want to set up Kaleidoscope as the default merge tool, then also set the following variables:
[mergetool]
    prompt = false
[merge]
    tool = Kaleidoscope
```

What are my next steps for troubleshooting or resolution?

**Comment by milke** [comment]
@ideologysec, this fix is now officially available in the form of a new official version **1.7.4 (build 117)**. However, at the beginning of this thread we touched the subject of **XDG_CONFIG_HOME** environment variable and the error you got trying to set it, so I'd like to explain it a bit, it may be helpful to someone else, getting the same error.

**XDG_CONFIG_HOME** environment variable is a part of [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/index.html#introduction), and it's purpose is define a single folder, where all user configuration files for different command line tools are located. [**Here**](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html) it states:

> `$XDG_CONFIG_HOME` defines the base directory relative to which user-specific configuration files should be stored. If `$XDG_CONFIG_HOME` is either not set or empty, a default equal to `$HOME/.config` should be used.

Core-git (official git version) respect this configuration setting and in case a user has **XDG_CONFIG_HOME** defined, git reads/writes configuration settings in `$XDG_CONFIG_HOME/git/config` file. As a proper Git client, GitFinder does the same. However, since GitFinder is fully sandboxed application, it can't access XDG git configuration file if **XDG_CONFIG_HOME** is set somewhere different than the default `$HOME/.config` location.

If you haven't set **XDG_CONFIG_HOME** environment variable, or it's empty, the default location `$HOME/.config` is used and GitFinder can access and use it, as it is automatically included in its sandbox environment. However, if you have a custom value for **XDG_CONFIG_HOME** (different than `$HOME/.config`), GitFinder cannot access that custom location automatically and you will have to select it in **Git Configuration… > General**, so that GitFinder can include selected location in its sandboxed environment. GitFinder will detect this case and will inform you. For example, I set **XDG_CONFIG_HOME** to `$HOME/.myconfig` and here is what GitFinder shows:
<img width="595" alt="Screen Shot 2021-11-01 at 12 13 09" src="https://user-images.githubusercontent.com/291305/139663212-5c591803-16c7-4f95-a32e-faabbac090dd.png">
GitFinder now expects you to select a folder at path `/Users/milke/.myconfig` and if you select anything else, it will show an error:
<img width="812" alt="Screen Shot 2021-11-01 at 12 13 46" src="https://user-images.githubusercontent.com/291305/139663418-826ff3b3-b3eb-4be3-b46a-ac371195a9f9.png">
This is exactly the same error you saw. In your case, the **XDG_CONFIG_HOME** environment variable is not set at all (so the default `$HOME/.config` is used), yet you want to select something else and hence you get that error. I hope it's clear what I'm talking about here. The only thing to fix here is that misleading "_folder at path "(null)",_" in the error message and I'll fix it in the next update.

Another important note here: environment variables for macOS GUI applications cannot be set simply by executing `export ENVAR="value"` in the terminal. That works only for command line (terminal) applications/tools. For GUI applications, you need to use `launchctl` command. A nice breakdown of that method can be found [here](https://www.dowdandassociates.com/blog/content/howto-set-an-environment-variable-in-mac-os-x-launchd-plist/).

If anything about **XDG_CONFIG_HOME** (and environment variables for GUI applications) is still unclear, please let me know.

**Comment by milke** [comment]
@ideologysec, since this has been resolved, and I also put some additional explanations regarding **XDG_CONFIG_HOME** environment variable, I'm closing this.
