### ISSUE TITLE
Let me get rid of context menu clutter

### ISSUE THREAD

**Issue by 3rdcycle** [milke/GitFinder-Issues#113]
I couldn't find a way to remove the "Application" section that's cluttering up my context menu.
![Screenshot 2022-02-21 at 10 56 18](https://user-images.githubusercontent.com/1217821/154932793-c4d94733-d037-4ff6-9507-68d936e3b352.png)

**Comment by milke** [comment]
@3rdcycle yeah, that's not possible at the moment. If you uncheck **Show menu bar icon** in the preferences, that _Application_ part will be automatically added to the contextual (and toolbar item) menu. The intention being to be able to access common GitFinder functionality in case you hide the menu bar icon. Because, if you hide that and there's no that added _Application_ part of the menu, the only option to access those functions is to open some GitFinder window (e.g. _Browser_) and then access the options from the main menu. But even that won't work if you choose **Never show Dock icon** from the preferences.

Anyway, it the next build I'll add an additional option to append the _Application_ part to menus in case the menu icon is hidden. And perhaps even the possibility to customize that part of the menu, like it's possible with _Git Repository_ and _Git Items_ parts.

**Comment by milke** [comment]
This is implemented in the latest beta version **1.7.5b2 (build 120)**. The _Application_ part of the menu is not automatically added to the contextual and toolbar item menus if **Show menu bar icon** is unchecked. Instead, the _Application_ part of the menus can be configured the same way as already existing _Git Repository and _Git Items_ parts. By default, none of the items from the _Application_ part is added to the menus.
<img width="590" alt="Screen Shot 2022-03-06 at 15 39 33" src="https://user-images.githubusercontent.com/291305/156928094-d6e128dd-688a-4f1c-9608-d0cf1ecc55ff.png">
You can download the lates beta [**here**](https://get.gitfinder.com/GitFinder_beta.dmg), but you can also update your current copy using in-app updater. Just make sure to check for the **Beta** release channel in the update preferences, like in the picture below.
<img width="495" alt="Screen Shot 2022-03-06 at 15 43 47" src="https://user-images.githubusercontent.com/291305/156928173-2d401c28-96f1-4626-8bf3-01d30a387626.png">
Let me know how it all works.
