### ISSUE TITLE
GitFinder ignoring ~/.gitignore_global

### ISSUE THREAD

**Issue by asegner** [milke/GitFinder-Issues#121]
I have the following global gitignore in my home

```
% cat ~/.gitignore_global
# OS files
.DS_Store
```

Going into a monitored folder with a green check icon badge and running `touch .DS_Store` causes the displayed icon badge to display a question mark. Right-click on the folder and select "See changes" displays the .DS_Store file which should be ignored. I would also expect the parent folder to maintain a green check.

**Comment by milke** [comment]
Have you defined your `~/.gitignore_global` as a file to be used for global ignore rules inside your git global configuration file (`~/.gitconfig`, `~/.config/git/config`, or anything else you may use for the custom `XDG_CONFIG_HOME` path) like this:

```
[core]
        excludesfile = ~/.gitignore_global
``` 

If you don't you don't have to do that, I'm just asking if you have it. Your answer will determine my further responses.

**Comment by asegner** [comment]
yes its defined in my .gitconfig
```
% grep .gitignore_global ~/.* 2>/dev/null
.gitconfig:	excludesfile = /Users/aaron/.gitignore_global
```

**Comment by milke** [comment]
Go to **Git Configuration** in the status item menu:

<img width="172" alt="Screenshot 2023-07-20 at 23 55 51" src="https://github.com/milke/GitFinder-Issues/assets/291305/ea02517b-3c13-47de-8883-349669a81178">

Select **Ignores** tab and you probably see something like this:

<img width="403" alt="Screenshot 2023-07-20 at 23 54 51" src="https://github.com/milke/GitFinder-Issues/assets/291305/60e38960-a5ac-461c-8b62-ad6bd931d035">
<img width="403" alt="Screenshot 2023-07-20 at 23 54 41" src="https://github.com/milke/GitFinder-Issues/assets/291305/37b134c6-62b1-4c1d-89dd-1528092c8276">

There's even the explanation for this:

<img width="531" alt="Screenshot 2023-07-20 at 23 55 13" src="https://github.com/milke/GitFinder-Issues/assets/291305/cc83db27-015b-4662-b756-438893047baf">

So, in the offered menu, select **Set File Path…** and in the file selector select your `~/.gitignore_global` file. Everything should  be properly ignored afterwards.

**Comment by asegner** [comment]
perfect, thanks, not sure how i missed that

**Comment by pboling** [comment]
I just had the same question, and this answered it.  I have a custom global gitignore setup also, and it is surprising to not have it be automagically inherited.

```
[core]
    excludesfile = /Users/pboling/.gitignore
```

**Comment by milke** [comment]
@pboling,
> …and it is surprising to not have it be automagically inherited.

This is due sandboxing. GitFinder is a sandboxed application (more thoughts about it [**here**](https://gitfinder.com/blog/gitfinder-and-macos-sandboxing/35)) and the only way for a sandboxed application to gain access to files outside of its sandbox environment (buried into `~/Library/Containers/app_bundle_identifier`) is to select a file in the open/save panel or to explicitly add file path in application entitlements during development.

GitFinder does that by adding file access entitlement for files with known locations, such are `~/.gitconfig` and `/.config/git/config`. Those are the standard git configuration locations and it would be even ridiculous to ask users to select them in the open panel in order to access them, so they are added into entitlements.

However, the location of the file defining global git ignores isn't standardized. It's set in the configuration files as `excludesfile` property and can be anything the user wants. Hence it isn't possible to add it into application sandbox environment with an entitlement, it's only possible by selecting the file in the open panel. And that's why GitFinder requires the user to do so.

The only help the application can offer, and GitFinder does it, is to analyze to configuration file, note the `excludesfile` setting, and then tell you that you still haven't selected that file in GitFinder (open panel), so that it can access it. Hence that "Ignores Path Mismatch" warning and menu item in git configuration window and long explanation in the popover under the help (?) button.
