### ISSUE TITLE
Why does GitFinder add `*` to the repo's exclude list?

### ISSUE THREAD

**Issue by cdzombak** [milke/GitFinder-Issues#23]
When I added a repository to GitFinder, it added the following lines to the repo's `.git/info/exclude` file:

```
#GitFinder
*
```

This caused IntelliJ IDEA to treat everything in the repo as ignored, and in general it seems wrong. The reason for this addition is not clear. Why is this exclusion added to the repo's exclude file?

**Comment by milke** [comment]
Uff, that's the tough one and I didn't expect it coming… I'll try to explain what's going on there.

If you look more closely (open that exclude file in a hex editor), you'll see that line is not just `*`, it's actually `*\x04\x05\x06`, so there are three non-displayable characters (EOT, ENQ, ACK) at the end. This is a bit hacky way to achieve Finder integration for removed files.

Suppose you trash/delete/move-out-of-repo a file. Now, you want to stage that change and eventually commit it, all from Finder. But how do you stage that file in Finder, when it's not in the repository anymore, hence no icon badge, no git menu commands? In such case, GitFinder adds a "placeholder" for the file. The placeholder is an empty file (0 size) with exactly the same name (and extension if one exists) like removed file, but with `\x04\x05\x06` characters added to the end. I opted for those characters, because they are really a part of the filename, but to user the file appears having the exact same name as the original removed file. Now, since those files are just placeholders, treated specifically by GitFinder and will be removed once you commit changes (or discard them), they should be ignored in the repository by git. Therefore GitFinder adds that line in the repo's exclude file of every repo it touches.

I tested this against many git clients (including git command line tool) and it worked fine. But apart from Xcode, I haven't tested it in any other IDE with git integration. It seems IntelliJ IDEA ignores all non-displayable characters.

I'll have to think about the solution. I'd also appreciate any suggestion.

**Comment by cdzombak** [comment]
Thanks for the explanation, @milke. That makes sense, but it does seem to me like something that's likely to cause compatibility issues like this.

> I'll have to think about the solution. I'd also appreciate any suggestion.

I would consider doing something similar, but with meaningful displayable characters — perhaps those tombstone files can be named like `main.c (removed)`.

**Comment by milke** [comment]
Very early (alpha) implementations used special file extension for "placeholder" files, but then I thought many users new to git (for which I thought GitFinder could be a viable git client since it's integrated in Finder) might get scared, like *"what the heck are now these files with strange names?!"

I'll definitely think about solution, probably again a special extension, but hidden and without possibility to "unhide" it (with custom ACL). Anyway, I think you should also contact IntelliJ IDEA guys, because I think what they do is also wrong; some people may really have files with non-displayable characters in their repos (for whatever reason) they want to ignore, and IntelliJ IDEA will completely disregard that.

**Comment by cdzombak** [comment]
> but then I thought many users new to git (for which I thought GitFinder could be a viable git client since it's integrated in Finder) might get scared, like "what the heck are now these files with strange names?!"

That's a fair concern. I wonder, though, if those same users might wonder "why is this file still here? I thought I deleted it."

> Anyway, I think you should also contact IntelliJ IDEA guys, because I think what they do is also wrong; some people may really have files with non-displayable characters in their repos (for whatever reason) they want to ignore, and IntelliJ IDEA will completely disregard that.

I will do that, too, but I suspect they'll be relatively slow with a fix.

**Comment by cdzombak** [comment]
I think this is a problem with a popular third-party plugin (https://github.com/hsz/idea-gitignore), not IntelliJ IDEA itself.

**Comment by mcfog** [comment]
Hit this issue today, and I think there's some possible improvement if the trick must be kept

- add some comment about this trick in the exclude file (or maybe link to this issue or some info page)
- hide this entry in the repo "Settings" window (I've tried to manually remove this entry several times actually)
![image](https://user-images.githubusercontent.com/524075/39293217-e8195b82-496a-11e8-9969-bc4aaa995ddc.png)

**Comment by milke** [comment]
@mcfog, the trick definitely has to stay, you can read about the reasons in the second message of this thread. However, I'll try and do a couple of things:

1) Try to implement in a sensible way the similar trick/system, but using some special file extension for those deleted files, like I've already tried during very first alpha implementations.

2) Introduce the preference settings to completely disable the trick/hack (regardless of file name suffix). One person reported having problem with huge project environment if some files were unexpectedly added, regardless of their name/extension/suffix. They would like to have this completely disabled, with the price of not being able to do anything with deleted/moved to trash files with GinFinder.

3) Also do what you suggest; ignore this entry in "Excludes", at leas in GitFinder. Other git clients will continue showing it though.

I'm a bit busy with some other things at the moment, but the things mentioned above are the first things on my list to do for the very next release. Thanks for suggestion.

**Comment by uliwitness** [comment]
These hidden files cause additional issues: They make it impossible to delete things in Xcode asset catalogs (and probably folder references as well). Whenever I delete an image in an asset catalog, it creates the empty file, preventing the asset's folder from going away. This in turn makes Xcode re-add that asset as an asset without any images in it.

**Comment by milke** [comment]
I'm preparing an update, which will handle this issue in the following manner:

* There will be an option to crate placeholder files for deleted/moved files. Turning their creation off should fix Xcode assets and similar problems.
* Even if one choses to keep those placeholder files, they will use dedicated extension, hence lines

`#GitFinder`
`*`

will be removed from the exclude list, removing causes of some other problems with other development tools.

I'm currently busy with some things not related to GitFinder, so this new version will come out in abut two weeks. Thanks for the patience.

**Comment by milke** [comment]
OK, I worked on this (later than I expected, sorry about that) and I think I've fixed all possible wrong scenarios in the latest beta of GitFinder. Here is how git-deleted placeholder files are handled now…

First of all, those files now have custom file extension **gitFinderDeleted**. This removes necessity for any special, non-displayable characters in the exclude list. When this new version of GitFinder encounters a repository, it will add following lines (if they don't exist already) in the exclude file:

`# GitFinder placeholder for git-deleted files.`
`# Don't remove this line, it's needed for proper functioning of GitFinder.`
`*.gitFinderDeleted`

Like suggested by @mcfog, the detailed comment should be enough to inform users what this exclude rule is all about and why it is needed. If your exclude file already contains previously created problematic lines:

`#GitFinder`
`*\x04\x05\x06`

they will be replaced with new ones. This should remove a cause of problems in IntelliJ IDEA and possibly other IDEs. Additionally, the new exclude rule can't be deleted in the GitFinder repo setting window, as **- (delete)** button is disabled, as in the picture below:
![repo_settings](https://user-images.githubusercontent.com/291305/43290322-14a0d63e-912e-11e8-8729-bfa68185f3fd.png)
As per @mcfog suggestion, my first implementation was hiding that rule completely, but then I worried some users may be wondering why it isn't in there whereas it is present in the exclude file. Hence I decided to leave it in, but will clear intention to show it should not be deleted.

The new file extension `gitFinderDeleted` is hidden on created placeholder files, so these files appear with the same name as their originals. As before, if you try to modify the file in any way (including showing file extension), you'll be asked to escalate privileges and this should be pretty clear indication these files should be left alone and you should only use them to execute git operations on them form the Finder contextual of toolbar item menu. If your browser already contains old placeholders (with suffix `\x04\x05\x06`), those will be replaced with new placeholders with `gitFinderDeleted` extension.

Finally, to avoid problems with assets catalogs in Xcode (and possibly similar potential problems in other IDEs) reported by @uliwitness, GitFinder now had an option to create (or not) these git-deleted placeholder files. It's in the GitFinder git config prefs, see the picture below:
![git_config_prefs](https://user-images.githubusercontent.com/291305/43290767-64d02974-912f-11e8-84b8-163d46f371ec.png)
If you opt not to create placeholder files, git-deleted files will not be represented in Finder and hence you will not be able to execute git operations on them from Finder, like e.g. _Stage_, _Unstage_, _Revert_, _See Changes_ and similar. However, if you opt to show git status for folders (see the picture above) and you execute any git operation on a parent folder of git-deleted file, GitFinder will be able to perform that operation (I hope it's clear what I'm talking about here, try it out yourself). Additionally, while git-deleted files aren't represented in Finder, they are still visible in the repository browser window, so you can perform all operations on deleted files from there, just like before.

All these changes are available in GitFinder version **1.0.2b1 (build 37)**. You can update to it from GitFinder update preferences, just choose **Beta** release channel, like in the picture below:
![update_prefs](https://user-images.githubusercontent.com/291305/43289790-555fee3c-912c-11e8-86d7-898e01a09651.png)
Please try/test/use all aspects of those changes. I tested smooth transition from old to new git-deleted placeholder files and all options an operations with them being created or not, but it may happen I missed something. I'd appreciate your feedback in any case, even if everything works smoothly so I can make this release official.

Once again, I apologise for delays and thanks for your patience. I hope changes are worth it.

**Comment by milke** [comment]
I've just made this officially available in version **1.0.2**. Hence, I'll close the issue. If it doesn't work correctly, or anyone have suggestions to improve behaviour in this regard further, feel free to reopen.
