### ISSUE TITLE
GitFinder windows should be persistent, function like a proper client

### ISSUE THREAD

**Issue by chrisdeeming** [milke/GitFinder-Issues#27]
Great work on this, it's got the potential to be a really nice client. I'm enjoying the Finder integration, but I don't think it's suitable for all operations.

I find that many windows that get opened, particularly the Browser, are totally lost if you navigate to another Finder window or another application.

For example, let's say I start staging files and writing a commit message, I might need to go back to my IDE to make some further changes, as soon as I go back to Finder, GitFinder is now nowhere to be seen.

There's no way to get back to it with Cmd+Tab or even Cmd+` within Finder, it also has no presence in the dock.

I think it would be cool if the Browser could be launched as a stand alone application which can be docked, and navigated to if it's open in the traditional way.

**Comment by milke** [comment]
You're not the first with this remark @chrisdeeming. My first intention was to make all windows floating, but then I realised that could be to intrusive and people wouldn't be able to see windows of other applications.
The most likely solution is a preference setting enabling GitFinder to work as a stand alone application, with menu bar, Dock icon and cmd+tab switching (plus Finder integration, of course), or to work mostly hidden, like it does now. I'll try to squeeze this setting on one of the upcoming updates.

**Comment by milke** [comment]
Version 1.2 implements some of the requested behaviour. GitFinder still doesn't behave like document-based application (like other git clients), so for example,  you can't open a new repository using menu commands. That was never the intention, but since numerous people have that request, GitFinder will move into that direction.

For now, version 1.2 brings new *General* preference setting named **Show Dock icon**. Possible values are:

- **Always** - Dock icon is shown all the time GitFinder is running.
- **When having windows** - Dock icon is shown if GitFinder is running and at lease one of its windows is shown.
- **Never** - Dock icon is never shown, GitFinder behaves as it has until version 1.2.

While Dock icon is shown, GitFinder menu (fairly empty at the moment) is also shown and you can switch to GitFinder with *cmd+tab*, like with any other application.

The default value for this new setting is *When having windows*. I think that's the best compromise between not being intrusive, yet being able to switch using cmd+tab if needed.
