### ISSUE TITLE
Auto-detect and -add repos

### ISSUE THREAD

**Issue by katrinleinweber** [milke/GitFinder-Issues#31]
As a contributor to many different projects, both privately and at work, I have repo folders all over my file system. Hence, it's a rather large burden of entry to testing and using GitFinder. Thankfully, for the few folders that contain many repos, multi-select was available :-)

Does the Finder API allow auto-detecting, whether a currently open folder is a repo (contains a `.git/`)? If yes, how about adding the functionality to auto-add repos to GitFinder so that the overlay icons and context menu options appear automatically when opening a repo folder.

**Comment by milke** [comment]
@katrinleinweber, what you ask is possible and that's exactly what GitFinder is already doing. Anyway, it still requires you to set a list of folders where to look for git repositories for two reasons:

1. GitFinder and all its components are fully sandboxed. Asking for folders in necessary in order to get them under GitFinder sandbox environment and get read/write access for them.
2. Finder Sync API requires setting of folders which to monitor (when they are entered/exited). Asking for folders is therefore also used to set Finder Sync API. Without asking, Finder Sync API wouldn't know which folders to monitor. Of course, I could've programmatically set, for example, the whole home folder to be monitored, but then many folders would be monitored completely unnecessarily (possibly affecting performance) and there still may be some git repositories left outside of the home folder, which would stay unmonitored.

Hence, asking for folders where git repositories are is necessary. I hope I was clear enough in explaining why. If you have any further questions, please don't hesitate to ask.

**Comment by katrinleinweber** [comment]
OK, thanks for explaining :-)

**Comment by milke** [comment]
@katrinleinweber, all the things you propose sound really nice and I've been thinking a lot about various possibilities how to implement all this in the most user friendly manner during GitFinder development. However, due to sandboxing, using open panel or drag'n'drop to add *"Repo Folders"* is necessary. Even if GitFinder detected *"found most of your Git repos in folder"* folders, it wouldn't be able to add them automatically, or better said, it would, but it wouldn't acquire necessary read/write access. Like said, using open panel or drag'n'drop is necessary to acquire those rights. It's all due to sandboxing and at the end I concluded the current implementation was the best compromise of doing necessary things and still preventing UI from becoming too bloated and complicated.

Now, whether GitFinder should be sandboxed or not is a completely different topic. I had my own reasons for doing it and very soon I will make a blog post about why I did it. But that can also change in the future, if further development proves too difficult or impossible with sandbox in play.

**Comment by jbandi** [comment]
If I add a "non-repository" folder that contains several independent git repository folders to "Repo Folders" in GitFinder preferences ... should then all the individual repositories be monitored?
It seems not to be working in my case, but I see several GitFinderSync processes taking a lot of CPU power ...

**Comment by milke** [comment]
@jbandi, only now I see that somehow I missed your post. I'm really sorry about that :-( Do you still have that problem?

**Comment by milke** [comment]
Sorry about that ;-(.  I really handled it badly. If you decide to come back I think you deserve a free license as my excuse for handling your issue poorly. Let me know if you want the license and if so, I'd need your full name and email address (you can send those using GitFinder support form [here](https://gitfinder.com/support)).
