### ISSUE TITLE
WebStorm always remind me 'You are editing  a file which is ignored' if i add project to Repo Folders

### ISSUE THREAD

**Issue by callmeDAY** [milke/GitFinder-Issues#36]
Another problem is that i can not click register button when i enter my License Key.

I bought it from bundlehunt.com.

version: 1.01(36)

**Comment by milke** [comment]
I'll try to figure out what that problem with WebStorm is. I don't use it, but the only thing that happens when you add a folder to "Repo Folders" is telling GitFinder Finder extension to monitor that folder, that operation doesn't even touch any repo or file or anything. I'd assume it's rather WebStorm's misbehaviour than GitFinder's.

As of your license, BundleHunt guys screwed there a little, they seem to send to some people different registration names in emails than those they used to register. Go to BundleHunt web site and find your registration name there (in the receipt for your purchase), it's probably different than the name specified in the email they sent to you.
