### ISSUE TITLE
Error checking and unchecking login item box

### ISSUE THREAD

**Issue by kamcma** [milke/GitFinder-Issues#41]
<img width="471" alt="screen shot 2018-09-24 at 9 02 59 p m" src="https://user-images.githubusercontent.com/5169528/45987048-713a8a00-c03d-11e8-8e6d-e5c09e37e8da.png">

I experienced this behavior in 1.0.x on High Sierra and now still in 1.1 on Mojave. Would be happy to provide more diagnostic information if you can tell me how. Both checking and unchecking, the error dialogue presents, but then the checkbox is checked or unchecked as if there had been no error.

Edit to add: just confirmed that even if you dismiss the error dialogue and leave the login item box checked, and then reboot, GitFinder does not launch on login. But then when I manually launch GitFinder, the login item box is still checked.

**Comment by milke** [comment]
That bug is a result of a terribly stupid omission (letter capitalisation) when changing bundle identifier for a launch process. It started in version **1.0.2** and is a prime example of _"don't fix it if it's working"_ rule.

Anyhow, I've fixed it and just uploaded new version (1.1.1, build 42) to the server. You can download it directly from [gitfinder.com](https://gitfinder.com), of use in-app updater.

Please let me know if it's also fixed for you and if so I'll close this one. Thanks for reporting it.

**Comment by kamcma** [comment]
Wow, that was fast! Thank you. Yes, it seems to be fixed. Login box checked with no error dialogue, rebooted and GitFinder was launched.

Love this app, thanks again.
