### ISSUE TITLE
Unable to Create a Tag with a "." in The Name

### ISSUE THREAD

**Issue by luxlogica** [milke/GitFinder-Issues#49]
It's quite common to use tag names that reflect version numbers - like "1.1", "1.2", "2.0", etc. This is often recommended when committing 'release' branches as part of a Git-Flow workflow.  Unfortunately, in GitFinder, when we try to type a "." in the middle of a tag name, we get a *beep*! - it seems tag names are not allowed to have dots in GitFinder.

**Comment by milke** [comment]
This is a bug in reference name formatter. Period/dot `'.'` is not allowed at the end (or beginning) of a reference name, but it is allowed anywhere in between. However, as you type the reference name with dot, it's normal it will appear at the end at some point while typing.

This is fixed in the latest beta **1.3.1b4 (build 61)**. `'.'` at the end of the reference name is allowed to type (so you can continue typing further), but in such case, GitFinder will disable further action while the reference name is invalid. Try it yourself, you'll understand what I mean. Let me know if everything works okay.

**Comment by luxlogica** [comment]
Thank you for being so prompt with the fix, @milke - indeed, it works as expected, and the way you've made the warning message appear when the name is invalid is actually **very helpful**. Thank you so much for all your work - it's truly appreciated.
