### ISSUE TITLE
GF cannot find BBEdit for diffs

### ISSUE THREAD

**Issue by azankl** [milke/GitFinder-Issues#57]
I chose BBEdit as my diff tool in GitFinder's Git Configuration. I did get a popup to install a script in GitFinder's script library, which I did. However, when I now choose to compare two files, I get a popup saying 'Could not locate application with bundle identifier com.barenbones.bbedit (see screenshot attached). I have BBEdit installed at /Applications/BBEdit and the BBEdit command line tools are installed and working normally.

<img width="532" alt="Screen Shot 2020-09-06 at 2 10 30 pm" src="https://user-images.githubusercontent.com/4812335/92318176-d1207480-f04b-11ea-931f-2b58c869904b.png">

**Comment by milke** [comment]
Hi @azankl, two questions:

**1.** What happens if you choose some other application as a diff tool, e.g. Apple's **FileMerge**?

**2.** Open the terminal and execute the following command:

`mdfind kMDItemCFBundleIdentifier=com.barebones.bbedit `

What do you see as an output to that command? From what you've said, the output should be `/Applications/BBEdit.app`.

**Comment by azankl** [comment]
`mdfind kMDItemCFBundleIdentifier=com.barebones.bbedit` showed:
`/Applications/BBEdit.app`
`/Users/azankl/.Trash/BBEdit.app`
Deleted the BBEdit.app in the Trash and it works now.
Thanks!

**Comment by milke** [comment]
It works now, but you actually revealed a bug in GitFinder's script for diff/merge tools… Namely, if a user has two or more copies of an application with particular bundle identifier installed in different locations (for example in **/Applications** and **~/Applications**), the multiline output of **mdfind** will confuse the script and it will fail to find requested application. That's exactly what happened in your case and it got *"fixed"* after you deleted one of the copies (in the Trash).

I'll leave this open and I'll close it once the issue is fixed in the next update of GitFinder. Thank for reporting this.

**Comment by milke** [comment]
I've just released version **1.5.1**, which fixes this bug. However, once you try to use any diff/merge tool you configured, this new version will ask you to install diff/merge tool support again :-(
<img width="532" alt="Screen Shot 2020-09-10 at 11 46 45" src="https://user-images.githubusercontent.com/291305/92715063-41d1d480-f35d-11ea-8eab-d3b99a07ce85.png">
Unfortunately, this is necessary as that's the only way (due to sandbox restrictions) to replace the old verson of the **tools** script.
