### ISSUE TITLE
"See Changes", "Commit" and most of all "History" open very slowly

### ISSUE THREAD

**Issue by ddobrev** [milke/GitFinder-Issues#64]
"See Changes" and "Commit" take 3 seconds each - this is enough for an unfamiliar user to think they don't work. "History" is much worse, taking at least 20 seconds.

**Comment by milke** [comment]
Hm, that's quite unusual, I don't see that behaviour. I tried the very same repository you mentioned in another thread (https://github.com/mono/CppSharp) and GitFinder me the history of ALL files in the repository (choosing **History** menu item on the repository root folder) almost instantly, see [**this**](https://www.icloud.com/iclouddrive/0fSuTt4UQxjYzRXO_Io1x0wsQ#history%5Fblame) video. Besides, even if some operation takes long time (like blame, which is notoriously slow in libgit2, I've been planing to improve it for a long time, but just can't find enough time to do it), the window should appear immediately and files should appear as they are being processed (shown in the same video, choosing **Blame** for the *src* subfolder). Similar with "See Changes" and "Commit".

Is your repository located on a local disk, or some mounted external or network volume?

**Comment by ddobrev** [comment]
It's a local disk, APFS. I can see you right-click a folder while I did the empty space within the repository but it makes no difference. It always happens to me while at the same time I've had no trouble with other applications. Would a video of my own help you?
Впрочем, ти си сърбин или хърватин, нали? Може би словенец? Разбираш ли български? :)

**Comment by milke** [comment]
Seeing a video from your side would certainly be interesting. I'm mostly interested to see if GitFinder's history window (with an empty files list in the sidebar) appears immediately with upper title **Processing…** and then the list gets populated with files (like in my blame example), or you actually have to wait for that window to appear, like 20 seconds or so…

Србин сам :-)  Не ”разбирам” баш бугарски, али сам провео годину дана у војсци у Македонији (док је још све било Југославија) и поприлично разумем макодонски, а то скоро да је исто :-)

**Comment by ddobrev** [comment]
I hope [this](https://streamable.com/omyvtj) helps. As you can see, "Processing" stays on for 2 or 3 seconds but before this I wait for almost double what I had thought.
Let me know if there's anything else I can do for easier reproduction.

Щом си бил в Македония, значи точно с български си имал досег. Нали знаеш: македонски "език" няма, само македонско българско наречие. ;)

**Comment by ddobrev** [comment]
I actually have an idea what this might be. This same project, CppSharp, uses Clang as a dependency. It's located in <root>/deps/llvm and ignored. Clang is huge and if the history by mistake crawls ignored files as well, this could explain the situation. To check, follow [this instruction](https://github.com/mono/CppSharp/blob/master/docs/GettingStarted.md#downloading-the-llvm-and-clang-packages) for Clang to appear and then see if the appearance of the history slows down. If it doesn't work, let me know because I have another option in mind.

**Comment by milke** [comment]
Actually, yes! The "only" thing that happens between menu item click and window appearance is the traversal of the clicked folder(s) hierarchy to figure out which files should be presented in the files list. That applies not only to history, but to all file related operations (those under *"Git Items"*), like (un)stage, commit, see changes, revert, etc… For example, for **See Changes**, hierarchy of clicked folder(s) are traversed to see which files are *"diffable"* (have changes). The shallower the hierarchy, the faster traversal. The extreme short case is clicking just files, and the repository root is on the other end of being extreme.

There's no other way of doing that, but actually I can make an improvement. For all those operations I was traversing ignored folders as well. Luckily, ignored folder can be recognised by git at its root, so I can immediately skip its traversal. I won't bother downloading Clang dependency, I'd be just interested to know how many files are there in that */deps/llvm* folder. I'm pretty sure that explains the behaviour.

I'll introduce this improvement in yet another beta and let you know when it's ready to try it out. Besides skipping ignored folders traversal, it will also make window appear immediately (at the moment the traversal starts), so that people with really huge repos (with "that" many files, none ignored) trying to execute commands on root (or close enough) folder would know the operation is in progress.

Ја сам провео шест месеци у караули на бугарској граници (Делчево - Благоевград). Што се тиче језика, нисам баш сигуран да би се Македонци (или бар већина) сложила са тобом. Али не бих да улазим у ту причу. Решите то (и Гоце Делчева и остало) између себе :-)

**Comment by ddobrev** [comment]
`<root>/deps/llvm` has 99762 files (this includes the source code of Clang because I had to also build it recently).
Looking forward to the new beta. :)

**Comment by milke** [comment]
Okay, getting back to this, I was busy with some other things…

I want to get that llvm dependencies directory and investigate behaviour, but I can't get it using [your instruction](https://github.com/mono/CppSharp/blob/master/docs/GettingStarted.md#downloading-the-llvm-and-clang-packages)… I need *premake5*, which I don't use, but okay I've installed it and after running required command I get *"Could not find Mono executable, please make sure it is in PATH."* and probably other dependencies would follow. As I really don't want to install a ton of things I don't really use, I'd appreciate if you could somehow provide your local copy of the repository (strip all eventual sensitive data from there) with *<root>/deps/llvm* already in there and send me a download link. I'd really appreciate that.

Thanks a lot 👍

**Comment by ddobrev** [comment]
The mistake's mine, I'd forgotten about Mono. Anyway, [here's my repository](https://ufile.io/f3qh27dz). It's a little large, 1 GB to download and 3 unpacked but then again, if it was small there would've been no problem. This way it's better because my copy also contains the source code of Clang which you wouldn't've got. Let me know if I can help further.

**Comment by milke** [comment]
I've just uploaded new beta **1.5.3b2 (build 83)**, you can update to it the same way as before. It improves traversing directories to get git statuses for files when ignored directories/files are present. Please check it out. There's still room for improvements in this regard and I plan to implement them, but I'm just interested if I'm on the right track.

**Comment by ddobrev** [comment]
Now they all appear immediately!

**Comment by milke** [comment]
See last comment in #63. Considering what things were fixed/improved, this was probably the better place to post it, but nevertheless.
