### ISSUE TITLE
A blocking dialogue sometimes appears right after starting the OS up

### ISSUE THREAD

**Issue by ddobrev** [milke/GitFinder-Issues#65]
The dialogue looks like this:

<img width="474" alt="Bildschirmfoto 2020-10-23 um 11 52 58" src="https://user-images.githubusercontent.com/5193072/97639866-1c517500-1a48-11eb-8a6d-0aa076f67f9f.png">

It blocks any actions through the tool-bar at the top left. If I click either button, it reappears. I must kill the process of GitFinder through "Force Quit" in order to make it work.
I cannot reproduce this reliably. It's happened a total of 2 times.

**Comment by milke** [comment]
That error appears when you browse into a folder (or any of its descendants) containing a repository, but GitFinder can't access it due to sandboxing restrictions, because it that repo folder (or any of its ascendants) in not in GitFinder's repo list in the preferences. But GitFinder can still see it somehow. Most likely through symlinks/aliases.

Let me give you two examples, so perhaps you're encountering one of them… As you already probably figured out, GitFinder can access (and monitor in Finder) only folders from the repo list in the preferences. So let's say you have folder `Projects` and you put it into GitFinder's repo list. Git Finder will be able to access all subfolders (supposedly git repos) in that folder. Then you put repo in folder `Project1` into parent `Projects` and GitFinder will access it. Then you put another repo `Project2` outside of `Projects` but in `Projects` you make a symlink/alias to it. Now, GitFinder can *"see"* it (since it's in `Projects`), but cannot open it, because it's outside of `Projects`. I hope you get what I mean…

Do you have anything similar?

**Comment by milke** [comment]
The other thing is probably a potential usability issue… I should probably show that error/dialog only the first time a user gets to the unaccessible repo (explained above) and after that ignore it. Currently, if you *Cancel* but later on browser into unaccessible repository again, the error will appear again.

**Comment by ddobrev** [comment]
Nothing similar, actually my set-up couldn't be simpler. A folder which is at the same time a git repository (.git is a direct child) and this same folder is added in the preferences of GitFinder.

**Comment by milke** [comment]
> Nothing similar, actually my set-up couldn't be simpler. A folder which is at the same time a git repository (.git is a direct child) and this same folder is added in the preferences of GitFinder.

Does that repo, by some chance, contains some symlinks/aliases to some other repos/submodules (outside of it)? Is the folder reported in quotation marks in the error dialog folder of that repo?

**Comment by ddobrev** [comment]
Yes, it is. About symlinks — no. It's the same repo I uploaded for you in another issue. The only piece which might have such is the folder with Clang but it's ignored.

**Comment by milke** [comment]
Well, there is only one case that particular error/dialog happens and that is if opening `repo/.git/config` fails with EPERM (Operation not permitted), which served to me as a sure sign the repo cannot be accessed due to sandboxing. I don't know if some other process messes up with the file and causes that… If you manage to find even vaguely consistent way to reproduce the error, please let me know.

BTW, all testing with new beta releases since you reported other problems I did with the copy of the repo(zipped) you sent me and I've never got that error :-(

**Comment by ddobrev** [comment]
I understand. I'll give you more information as soon as I can.
Fortunately, working around it is pretty quick and simple.

**Comment by milke** [comment]
This is quite similar to #70, so solving that one in the upcoming **1.6.1 beta** should also solve this one.

**Comment by milke** [comment]
I've just uploaded **1.6.1b1**, you can update your current copy to it by checking for the **Beta** channel in the update preferences. Check it out and let me know if you see that message reported (when not needed) again.

**Comment by ddobrev** [comment]
@milke done. I haven't encountered it any more after I reported it but then again, I've been using GitFinder much less lately (not in favour of other clients but of other work). I tend to think this has been fixed so I'm closing it. I'm definitely going to report and reopen should it happen again.
