### ISSUE TITLE
[Bug] After Update, GitFinder Cannot Find Global .gitconfig

### ISSUE THREAD

**Issue by luxlogica** [milke/GitFinder-Issues#69]
I have just upgraded to GitFinder 1.6, running MacOS Big Sur 11.0.1. After launching GitFinder, I get the following message:

<img width="283" alt="Screen Shot 2020-11-14 at 11 01 40 am" src="https://user-images.githubusercontent.com/2994472/99132366-fe9c2680-2669-11eb-960e-2229901cb629.png">

Going to the 'Git Preferences' menu, it does seem like my (previously set) global git settings have disappeared!... 🤷‍♂️

Suggestion: even if the global .gitconfig cannot be found/read, it might more helpful - specially for new users - if the warning was a little friendlier, e.g. "Please set your Global Git Preferences by going to the 'Git Preferences...' menu".

**Comment by milke** [comment]
> … it does seem like my (previously set) global git settings have disappeared!…

For some reason, your `~/.gitconfig` file got deleted. The only thing I can tell you regarding that is that GitFinder certainly **DID NOT** do that! It creates some configuration files (`.gitignore`, `.gitattributs`, `.gitmodules`…) when necessary, but it never deletes any.

> Suggestion: even if the global .gitconfig cannot be found/read, it might more helpful - specially for new users - if the warning was a little friendlier, e.g. "Please set your Global Git Preferences by going to the 'Git Preferences...' menu".

I agree, but I'm actually considering ignoring absence of `~/.gitconfig` altogether, because the core git does that too and it should not affect further operations. The error above doesn't affect further operations either, but it probably shouldn't be reported at all.

The modification will appear in the first beta of **1.6.1**.

**Comment by milke** [comment]
I've just uploaded **1.6.1b1**. You can update your current copy by checking the **Beta** channel in the update preferences. This version silently ignores absence of `~/.gitconfig` file, just like the git-core tool does. If you try to set any global configuration value from GitFinder's configuration window, the missing global configuration file will be created (and used afterwards) and set values written into it.

**Comment by milke** [comment]
Okay, I consider this fixed (the fix is now in the official release **1.6.1**), so I'm closing this. If the issue reappears, feel free to reopen.
