### ISSUE TITLE
You do not have permission to run the application “GitFinderSignIn.app”.

### ISSUE THREAD

**Issue by dvhwgumby** [milke/GitFinder-Issues#82]
Just downloaded the app and installed it.  I am running 11.5.1.  

In the "hosting" page: when I try to log into GitHub, GitLab, or BitBucket I get the warning 'You do not have permission to run the application “GitFinderSignIn.app”.'  FWIW: I looked at that file and I have execute permission.

**Comment by milke** [comment]
A few other people reported the same problem. The workaround for your problem is quite simple. Reveal GitFinder application bundle contents and locate “ag.zigz.GitFinder.HostsService.xpc” in “Contents/XPCServices” subfolder, like in the picture below:
<img width="769" alt="HostService" src="https://user-images.githubusercontent.com/291305/127192367-a42f984e-7388-4464-93db-9c1888b7824f.png">
Then in the same way reveal HostService bundle contents and locate “GitFinderSignIn” application in the “Contents/Helpers” subfolder, like in the picture below:
<img width="605" alt="SignIn" src="https://user-images.githubusercontent.com/291305/127192393-b7e2c7dd-227b-41fd-a134-561b66edf77f.png">
Double-click the GitFinderSignIn application to launch it, don’t worry if you don’t see any visual clues that it’s running. Now go back to using GitFinder and try signing to GitHub. It should work and once you finish signing in, GitFinder will take care of terminating GitFinderSignIn application. You need to do this ONLY ONCE. After that, it all will work normally.

I apologise for the trouble. I still don’t know why it happens on some systems. Out of my 8 macOS installations on different machines (real and virtual), I saw this error only on one, but I still couldn’t figure out why it happened. I guess some particular LaunchServices issue may cause it. I'll try to figure it out and fix it.

**Comment by milke** [comment]
Hi @dvhwgumby, I just wanted to let you know that I've just uploaded new beta version **1.7.2b3 (build 107)** and it fixes (or at least it should :-)) this issue, so the workaround I’ve explained in my previous response isn’t necessary anymore. I’d appreciate if you give this beta version a try and confirm everything works fine regarding signing into git host service accounts.

You can download the new beta [**here**](https://get.gitfinder.com/GitFinder_beta.dmg), but you can also upgrade your current copy automatically, just select Beta release channel, like below:
<img width="495" alt="update" src="https://user-images.githubusercontent.com/291305/127513692-3bd5021f-d0f6-4c51-b74e-50c3c72bd43f.png">

**Comment by dvhwgumby** [comment]
Works, thanks!
